import assert from 'node:assert/strict'
import { cp, mkdir, mkdtemp, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises'
import { lstatSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
const root=resolve('.');assert.equal(process.version,'v24.15.0','isolated runtime requires the exact pinned Node patch');const canonicalRoot=await realpath(root);const donor='a3439a3c7d7e7b3c9cfc505e833525376e8558d0';const temp=await mkdtemp(join(tmpdir(),'agent-real-clone-'));const canonicalTemp=await realpath(temp);const stage=join(temp,'staging-worktree');const fresh=join(temp,'fresh-clone');const fixtures=join(temp,'submodule-fixtures');const bin=join(temp,'bin');const gitEnv={...process.env,GIT_ALLOW_PROTOCOL:'file',GIT_TERMINAL_PROMPT:'0'}
function run(command,args,{cwd=root,env=process.env,input,allowFailure=false}={}){const result=spawnSync(command,args,{cwd,env,input,encoding:Buffer.isBuffer(input)?undefined:'utf8',maxBuffer:64*1024*1024});if(!allowFailure)assert.equal(result.status,0,`${command} ${args.join(' ')}\n${String(result.stdout)}\n${String(result.stderr)}`);return result}
function sourceUntracked(){return run('git',['ls-files','--others','--exclude-standard','-z']).stdout.split('\0').filter(Boolean).filter(path=>!path.startsWith('evidence/'))}
async function copyUntracked(destination,listed){for(const rel of listed){const source=join(root,rel);const target=join(destination,rel);await mkdir(dirname(target),{recursive:true});if(lstatSync(source).isSymbolicLink())await symlink(await realpath(source),target);else await cp(source,target,{recursive:true})}}
try{
 const sourceHead=run('git',['rev-parse','HEAD']).stdout.trim();const patch=run('git',['diff','--binary','--full-index','HEAD']).stdout;const untracked=sourceUntracked();const sourceDirty=patch.length>0||untracked.length>0;if(process.env.AGENT_REQUIRE_CLEAN_HEAD==='1')assert.equal(sourceDirty,false,'source has tracked changes or untracked source files; commit before clean-HEAD clone proof')
 let cloneSource=root;let snapshotCommit=sourceHead;let snapshotMode='tracked-head'
 if(sourceDirty){run('git',['clone','--no-hardlinks','--no-recurse-submodules',root,stage],{cwd:temp,env:gitEnv});const patchPath=join(temp,'working-tree.patch');await writeFile(patchPath,patch);if(patch.length>0)run('git',['apply','--index',patchPath],{cwd:stage,env:gitEnv});await copyUntracked(stage,untracked);run('git',['add','-A'],{cwd:stage,env:gitEnv});run('git',['config','user.name','work-1.1 isolated fixture'],{cwd:stage,env:gitEnv});run('git',['config','user.email','work-1.1@invalid'],{cwd:stage,env:gitEnv});run('git',['commit','-m','work-1.1 isolated verification snapshot'],{cwd:stage,env:gitEnv});cloneSource=stage;snapshotCommit=run('git',['rev-parse','HEAD'],{cwd:stage,env:gitEnv}).stdout.trim();snapshotMode='ephemeral-commit-from-full-source-diff'}
 assert.equal(run('git',['merge-base','--is-ancestor',donor,snapshotCommit],{cwd:cloneSource,env:gitEnv,allowFailure:true}).status,0,'snapshot must retain pinned donor ancestry')
 await mkdir(fixtures,{recursive:true});const localSources={'https://github.com/ccch1mneyyy/dsh-auth.git':join(root,'packages/tui/dsh-auth'),'https://github.com/T-Auto/dsh-ecosystem-spec.git':join(root,'packages/tui/dsh-ecosystem-spec'),'https://github.com/Yan-Zero/dsh-std.git':join(root,'packages/tui/vendor/dsh-std')};const rewrites=[];let fixtureIndex=0
 for(const [url,source] of Object.entries(localSources)){const bare=join(fixtures,`module-${fixtureIndex++}.git`);run('git',['clone','--bare','--no-hardlinks',source,bare],{cwd:temp,env:gitEnv});rewrites.push('-c',`url.file://${bare}.insteadOf=${url}`)}
 run('git',['-c','protocol.file.allow=always',...rewrites,'clone','--no-hardlinks','--recurse-submodules',cloneSource,fresh],{cwd:temp,env:gitEnv});assert.equal(run('git',['rev-parse','HEAD'],{cwd:fresh,env:gitEnv}).stdout.trim(),snapshotCommit);assert.equal(run('git',['status','--porcelain'],{cwd:fresh,env:gitEnv}).stdout.trim(),'');const submodules=run('git',['submodule','status','--recursive'],{cwd:fresh,env:gitEnv}).stdout.trim().split('\n').filter(Boolean);assert.equal(submodules.length,4);assert.ok(submodules.every(line=>!line.startsWith('-')&&!line.startsWith('+')&&!line.startsWith('U')))
 const declaredPnpm=process.env.AGENT_PNPM_EXEC_PATH;assert.ok(declaredPnpm&&isAbsolute(declaredPnpm),'AGENT_PNPM_EXEC_PATH must be an absolute canonical pnpm entrypoint');const pnpm=await realpath(declaredPnpm);assert.equal(pnpm,declaredPnpm,'AGENT_PNPM_EXEC_PATH must already be canonical');assert.equal(lstatSync(pnpm).isFile(),true,'canonical pnpm entrypoint must be a regular file');const pnpmProbe=run(process.execPath,[pnpm,'--version'],{env:{...process.env,NODE_OPTIONS:'',NODE_PATH:''}});assert.equal(pnpmProbe.stdout.trim(),'11.25.0','isolated runtime requires pnpm 11.25.0');await mkdir(bin,{recursive:true});await symlink(process.execPath,join(bin,'node'));const network=join(temp,'network.json');const modules=join(temp,'modules.txt');await writeFile(modules,'')
 const env={...process.env,PATH:`${bin}:/usr/bin:/bin`,NODE_PATH:'',STOKD_BIN:'/definitely/unavailable/stokd',STOKD_API_URL:'http://127.0.0.1:1',MONGODB_URI:'',AGENT_NETWORK_TRACE:network,AGENT_MODULE_TRACE:modules,GIT_ALLOW_PROTOCOL:'file',GIT_TERMINAL_PROMPT:'0'};assert.notEqual(spawnSync('sh',['-c','command -v stokd'],{cwd:fresh,env}).status,0)
 const canonicalFresh=await realpath(fresh);const inside=(base,path)=>{const rel=relative(base,path);return rel===''||(!isAbsolute(rel)&&rel!=='..'&&!rel.startsWith(`..${sep}`))};assert.ok(inside(canonicalTemp,canonicalFresh),'fresh clone must remain inside canonical temp root')
 run(process.execPath,[pnpm,'install','--frozen-lockfile','--ignore-scripts','--prefer-offline'],{cwd:fresh,env});const packages=['@stokd-cloud/agent-protocol','@stokd-cloud/agent-runtime','@stokd-cloud/agent-storage','@stokd-cloud/agent-dsh','@stokd-cloud/agent-stokd-bridge','@stokd-cloud/agent-api','@stokd-cloud/agent-host','@stokd-cloud/agent-cli'];run(process.execPath,[pnpm,...packages.flatMap(name=>['--filter',name]),'-r','build'],{cwd:fresh,env});run(process.execPath,[pnpm,'--filter','@deepseek-harness-tui/dsh-tui','run','build:cloud-agent-client'],{cwd:fresh,env});run(process.execPath,[pnpm,'verify:structure','--item','1.1'],{cwd:fresh,env})
 run(process.execPath,['--experimental-loader','./tests/work-1.1/module-trace-loader.mjs','--import','./tests/work-1.1/network-guard.mjs','./tests/work-1.1/import-targets.mjs'],{cwd:fresh,env});const attempted=JSON.parse(await readFile(network,'utf8'));assert.deepEqual(attempted,[]);const observed=[...new Set((await readFile(modules,'utf8')).trim().split('\n').filter(Boolean).map(fileURLToPath))];const loaded=[...new Set(await Promise.all(observed.map(path=>realpath(path))))];assert.ok(loaded.length>0);assert.ok(loaded.every(path=>inside(canonicalFresh,path)),`module resolved outside fresh clone: ${loaded.filter(path=>!inside(canonicalFresh,path)).join(',')}`);assert.ok(loaded.every(path=>!inside(canonicalRoot,path)),'module resolved from original checkout');assert.ok(loaded.every(path=>!path.includes('/packages/tui/')),'module resolved from TUI');assert.ok(loaded.every(path=>!path.includes('/mono/')),'module resolved from Mono');const product=loaded.filter(path=>path.includes('/packages/')||path.includes('/apps/'));assert.ok(product.length>=8);assert.ok(product.every(path=>path.includes('/lib/')));assert.ok(product.every(path=>!path.includes('/src/')));for(const name of ['protocol','runtime','storage','dsh','stokd-bridge'])assert.ok(product.some(path=>path.includes(`/packages/${name}/lib/`)));for(const name of ['api','host','cli'])assert.ok(product.some(path=>path.includes(`/apps/${name}/lib/`)));assert.equal(run('git',['status','--porcelain'],{cwd:fresh,env:gitEnv}).stdout.trim(),'')
 console.log(JSON.stringify({ok:true,source:'real-fresh-git-clone',sourceHead,snapshotCommit,snapshotMode,donorAncestor:donor,untrackedSourceFilesCommitted:untracked.length,recursiveSubmodules:submodules,gitAllowedProtocols:['file'],frozenInstall:true,npmInstallMode:'prefer-offline',pnpmVersion:pnpmProbe.stdout.trim(),standaloneStructureVerified:true,tuiAdapterBuild:'cloud-agent-client-only',packages,importAttemptedNetwork:attempted,loadedProductModules:product.map(path=>relative(canonicalFresh,path)),allFileModulesInsideFreshClone:true,parentNodeModules:false,mono:false,stokd:false,tuiImports:false}))
}finally{await rm(temp,{recursive:true,force:true})}
