# ── Generated service credentials ─────────────────────────────────────────────
# The SST layout produced these through a nested CloudFormation stack purely to
# borrow GenerateSecretString, so the plaintext never entered SST state. The
# Terraform provider has no equivalent generator, so the value is generated by
# `random_password` and therefore DOES land in Terraform state.
#
# That trade is why backend.tf makes encrypted remote state a hard requirement
# rather than a convention. It is called out in handoff/BEHAVIORAL-CONTRACT.md
# as a deliberate, reviewable difference from the SST scaffold.

locals {
  secret_kinds = ["runtime", "migration", "backup"]
}

resource "random_password" "service" {
  for_each = toset(local.secret_kinds)

  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "service" {
  for_each = toset(local.secret_kinds)

  name       = "stokd-agent-${var.stage}-${each.key}"
  kms_key_id = aws_kms_key.data.arn
  tags       = local.persistent_tags

  # Matches the CloudFormation DeletionPolicy/UpdateReplacePolicy: Retain that
  # the SST scaffold set. A deleted credential orphans its encrypted data.
  recovery_window_in_days = 30

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_secretsmanager_secret_version" "service" {
  for_each = aws_secretsmanager_secret.service

  secret_id     = each.value.id
  secret_string = random_password.service[each.key].result

  lifecycle {
    # The restore stage rotates its own credential material in place during a
    # restore. Terraform must not fight that.
    ignore_changes = [secret_string]
  }
}

# The restore stage reads the source stage's retained credentials to open the
# backup it is restoring. Read-only, and only in that direction.
data "aws_secretsmanager_secret" "source" {
  for_each = local.is_restore ? toset(local.secret_kinds) : toset([])

  name = "stokd-agent-${local.source_stage}-${each.key}"
}

locals {
  source_secret_arns = local.is_restore ? [for kind in local.secret_kinds : data.aws_secretsmanager_secret.source[kind].arn] : []

  runtime_secret_arn   = aws_secretsmanager_secret.service["runtime"].arn
  migration_secret_arn = aws_secretsmanager_secret.service["migration"].arn
  backup_secret_arn    = aws_secretsmanager_secret.service["backup"].arn

  source_runtime_secret_arn   = local.is_restore ? data.aws_secretsmanager_secret.source["runtime"].arn : local.runtime_secret_arn
  source_migration_secret_arn = local.is_restore ? data.aws_secretsmanager_secret.source["migration"].arn : local.migration_secret_arn
  source_backup_secret_arn    = local.is_restore ? data.aws_secretsmanager_secret.source["backup"].arn : local.backup_secret_arn
}
