/**
 * Pixel-whale animation frames for the startup splash, converted from
 * the hand-drawn Excel art in `whale_frames.zip` (25x40 cells, palette
 * alphabet shared with Whale.tsx: D outline, B body, L belly, W mouth,
 * `.` transparent). `OPENING_SEQUENCE` plays once at startup: blink,
 * water-spout bloom, tail wag, then the header settles static.
 */

/** One animation frame: 25 sprite rows of 40 palette characters. */
export interface WhaleFrame {
  /** Frame label from the source art (Chinese names kept for traceability). */
  readonly name: string
  readonly rows: readonly string[]
}

/** The 13 hand-drawn frames. */
export const WHALE_FRAMES: readonly WhaleFrame[] = [
  {
    name: 'standard',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '.......................DBD.......D......',
      '.......................DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'blink',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '.......................DBD.......D......',
      '.......................DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'fin1',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '.......................DBD.......D......',
      '.......................DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBBDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBBD.............',
      '......DDLLLWWWWWWLLLDBBBBBBDD...........',
      '........DLLLLLLLLLLLLDDBBBBBBD..........',
      '.........DDDDDDDDDDDD..DDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'fin2',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '.......................DBD.......D......',
      '.......................DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDDBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBBBDD............',
      '.....DLLLWWWWWWWWWWDBBBBBBBBDD..........',
      '......DDLLLWWWWWWLLLDBBBBBBBBBD.........',
      '........DLLLLLLLLLLLLDDDBBBBBD..........',
      '.........DDDDDDDDDDDD...DDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout1',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '.......................DBD.......D......',
      '.......................DBBD.....DBD.....',
      '..........LLL..........DBBBD..DDBBD.....',
      '...........L...........DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout2',
    rows: [
      '........................................',
      '........................................',
      '........................D...............',
      '...........L...........DBD.......D......',
      '.........LLLLL.........DBBD.....DBD.....',
      '..........LLL..........DBBBD..DDBBD.....',
      '...........L...........DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout3',
    rows: [
      '........................................',
      '........................................',
      '...........L............D...............',
      '.........LLLLL.........DBD.......D......',
      '.......LLLLLLLLL.......DBBD.....DBD.....',
      '..........LLL..........DBBBD..DDBBD.....',
      '...........L...........DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout4',
    rows: [
      '........................................',
      '...........L............................',
      '........LLLLLLL.........D...............',
      '......LLLLLLLLLLL......DBD.......D......',
      '......L...LLL...L......DBBD.....DBD.....',
      '...........L...........DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout5',
    rows: [
      '........................................',
      '.......LL..L..LL........................',
      '......LLLL.L.LLLL.......D...............',
      '.....L....LLL....L.....DBD.......D......',
      '....L......L......L....DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'spout6',
    rows: [
      '........................................',
      '......LL...L...LL.......................',
      '.....L..LL.L.LL..L......D...............',
      '....L.....LLL.....L....DBD.......D......',
      '...L.......L.......L...DBBD.....DBD.....',
      '.......................DBBBD..DDBBD.....',
      '.......................DBBBBDDBBBBD.....',
      '.......DDDDDDDDD........DBBBBBBBBD......',
      '......DBBBBBBBBBDD.......DBBBBBBBD......',
      '.....DBBBBBBBBBBBBDD.....DBBBBBDD.......',
      '....DBBBBBBBBBBBBBBBDD....DBBBD.........',
      '...DDBBBBBBBBBBBBBBBBBD..DBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBD..........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBD...........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'tail1',
    rows: [
      '........................................',
      '........................................',
      '.........................D..............',
      '........................DBD.......D.....',
      '........................DBBD.....DBD....',
      '........................DBBBD..DDBBD....',
      '.........................DBBBDDBBBBD....',
      '.......DDDDDDDDD.........DBBBBBBBBD.....',
      '......DBBBBBBBBBDD........DBBBBBBBD.....',
      '.....DBBBBBBBBBBBBDD......DBBBBBDD......',
      '....DBBBBBBBBBBBBBBBDD.....DBBBD........',
      '...DDBBBBBBBBBBBBBBBBBD...DBBBBD........',
      '...DBBBBBBBBBBBBBBBBBBBDDDBBBBBD........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBD..........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBBD..........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'tail2',
    rows: [
      '........................................',
      '........................................',
      '..........................D.............',
      '.........................DBD........DD..',
      '.........................DBBD......DBD..',
      '.........................DBBBD....DBBD..',
      '..........................DBBBD.DDBBD...',
      '.......DDDDDDDDD...........DBBBDBBBBD...',
      '......DBBBBBBBBBDD.........DBBBBBBBD....',
      '.....DBBBBBBBBBBBBDD........DBBBBBD.....',
      '....DBBBBBBBBBBBBBBBDD......DBBBBBD.....',
      '...DDBBBBBBBBBBBBBBBBBD..DDDBBBBDD......',
      '...DBBBBBBBBBBBBBBBBBBBDDBBBBBBBD.......',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBBD........',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBD.........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBBD.........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBBD..........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBD...........',
      '....DLLWWWWWWWWWWWWDBBBBDDBD............',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
  {
    name: 'tail3',
    rows: [
      '........................................',
      '........................................',
      '........................................',
      '.............................D..........',
      '............................DBD.........',
      '............................DBD.........',
      '...........................DBBD.....DD..',
      '.......DDDDDDDDD...........DBBBD...DBBD.',
      '......DBBBBBBBBBDD.........DBBBD.DDBBD..',
      '.....DBBBBBBBBBBBBDD.......DBBBBDBBBBD..',
      '....DBBBBBBBBBBBBBBBDD......DBBBBBBBD...',
      '...DDBBBBBBBBBBBBBBBBBD...DDBBBBBBBD....',
      '...DBBBBBBBBBBBBBBBBBBBDDDBBBBBBBBD.....',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBBBDD......',
      '...DBBBDBBBBBBDBBBBBBBBBBBBBBBBD........',
      '...DBBBBBBBBBBBBBBBBBBBBBBBBBBBD........',
      '...DBBBBWWWWWWWBBBBBBBBDBBBBBBD.........',
      '...DDBWWWWWWWWWWWWBBBBBBDBBBDD..........',
      '....DLLWWWWWWWWWWWWDBBBBDDBDD...........',
      '.....DLLLWWWWWWWWWWDBBBBBDD.............',
      '......DDLLLWWWWWWLLLDBBBBBDD............',
      '........DLLLLLLLLLLLDDBBBBBBD...........',
      '.........DDDDDDDDDDD..DDDDDDD...........',
      '........................................',
      '........................................',
    ],
  },
]

/** One step of the opening animation: frame index + dwell time. */
export interface OpeningStep {
  /** Index into WHALE_FRAMES. */
  readonly frame: number
  /** How long the frame stays on screen, in milliseconds. */
  readonly ms: number
}

/** Startup sequence (~3.4s), ending on the standard pose. */
export const OPENING_SEQUENCE: readonly OpeningStep[] = [
  { frame: 0, ms: 400 }, // standard
  { frame: 1, ms: 250 }, // blink
  { frame: 0, ms: 300 }, // standard
  { frame: 4, ms: 150 }, // spout1
  { frame: 5, ms: 150 }, // spout2
  { frame: 6, ms: 150 }, // spout3
  { frame: 7, ms: 150 }, // spout4
  { frame: 8, ms: 150 }, // spout5
  { frame: 9, ms: 150 }, // spout6
  { frame: 0, ms: 250 }, // standard
  { frame: 10, ms: 170 }, // tail1
  { frame: 11, ms: 170 }, // tail2
  { frame: 12, ms: 260 }, // tail3
  { frame: 11, ms: 170 }, // tail2
  { frame: 10, ms: 170 }, // tail1
  { frame: 0, ms: 300 }, // standard
]
